name: "pokedex cd"

on:
    workflow_run:
        workflows: ['pokedex']
        types:
            - completed
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: "setup node js"
              uses: actions/setup-node@v6
              with:
                node-version: '21'
            
            - name: "checking node version"
              run: "node --version"

            - name: "Setup versel cli"
              run: npm i -g vercel
            
            - name: "download build file"
              uses: actions/download-artifact@v7
              with:
                name: build
                run-id: ${{github.event.workflow_run.id}}
                github-token: ${{github.token}}
            
            - name: "Deploy to Vercel"
              run: vercel --prod --token=${{secrets.VERCEL_TOKEN}} --confirm --name=cicdproject