name: "pokedex"

on:
  push:
    branches:
        - master
  workflow_dispatch:

jobs:
    pokedex:
      runs-on: ubuntu-latest
      steps:
        - name: "checkout the project"
          uses: actions/checkout@v2

        - name: "checking the list"
          run: "ls"
                  
        - name: "upload production ready build files"
          uses: actions/upload-artifact@v6
          with:
            name: build
            path: dist
                  

        

